---
title: "p8105_hw5_jc5924"
output: github_document
name: Sophie Chen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```
## Problem 2
### Describe the data
```{r}
homicides=read_csv("./data/homicide-data.csv")
```
* In this homicides datafrmame, we have `r nrow(homicides)` of observations and `r ncol(homicides)` of variable that are `r names(homicides)`.

### Create a city_state variable and summarize the unsolved cases
```{r}
homicides_summary=homicides %>% 
  janitor::clean_names() %>% 
  mutate(city_state=str_c(city,state,sep = ", "),
         status=case_when(disposition=="Closed by arrest"~"solved",
                          disposition=="Closed without arrest"~"unsolved",
                          disposition=="Open/No arrest"~"unsolved")) %>% 
  group_by(city_state) %>% 
  summarize(homicides_number=n(),
            unsolved=sum(status=="unsolved"))
homicides_summary
```
### Proportion of unsolved homicides
```{r}
baltimore=prop.test(homicides_summary %>% filter(city_state=="Baltimore, MD") %>% 
                      pull(unsolved),
                    homicides_summary %>% filter(city_state=="Baltimore, MD") %>% 
                      pull(homicides_number)) %>% 
  broom::tidy() %>% 
  saveRDS(., "./data/baltimore_prop_test.rds")
```
### Prop.test for each of the cities 
```{r}
cities=homicides_summary %>% 
  mutate(prop_test=map2(.x=unsolved, .y=homicides_number, ~prop.test(x = .x, n = .y)),
         tidy=map(.x = prop_test, ~ broom::tidy(.x))) %>% 
  select(city_state,homicides_number,unsolved,tidy) %>% 
  unnest(tidy) %>% 
  select(city_state, estimate, conf.low, conf.high)
cities
```






